package com.hash.converter.util;

public enum Units {
    KILOMETER, METER, DECIMETER, CENTIMETER, MILLIMETER, MICROMETER, NANOMETER, PICOMETER,
    LIGHT_YEAR, PARSEC, LUNAR_DISTANCE, ASTRONOMICAL_UNIT,
    INCH, MILE, FOOT, YARD, NAUTICAL_MILE, FATHOM, FURLONG,

    SQUARE_KILOMETER, HECTARE, ARE, SQUARE_METER, SQUARE_DECIMETER, SQUARE_CENTIMETER, SQUARE_MILLIMETER,
    ACRE, SQUARE_MILE, SQUARE_YARD, SQUARE_FOOT, SQUARE_INCH, ROOD,

    CUBIC_METER, HECTOLITER, DECILITER, LITER, CENTILITER, MILLILITER, CUBIC_DECIMETER, CUBIC_CENTIMETER,
    CUBIC_INCH, CUBIC_FOOT, CUBIC_YARD, ACRE_FOOT,
    GALLON, FLUID_OUNCE,

    KILOGRAM, GRAM, MILLIGRAM, MICROGRAM, TONNE, QUINTAL, CARAT,
    POUND, OUNCE, GRAIN, LONG_TON, SHORT_TON, LONG_HUNDREDWEIGHT, SHORT_HUNDREDWEIGHT, STONE, DRAM,

    CELSIUS, FAHRENHEIT, KELVIN,

    WATT, KILOWATT, MEGAWATT, GIGAWATT,
    MILLIWATT, MICROWATT,
    HORSEPOWER_MECHANICAL, HORSEPOWER_METRIC, BTU_PER_HOUR, FOOT_POUND_PER_SECOND,

    METERS_PER_SECOND, KILOMETERS_PER_HOUR, MILES_PER_HOUR, FEET_PER_SECOND, KNOT, MACH, SPEED_OF_LIGHT,

    BINARY, DECIMAL, HEXADECIMAL, OCTAL,

    PASCAL, HECTOPASCAL, KILOPASCAL, MEGAPASCAL, BAR, MILLIBAR, ATMOSPHERE, TORR, PSI, INHG, MMHG,

    BIT, NIBBLE, BYTE, KILOBYTE, MEGABYTE, GIGABYTE
}
